# Generated by Django 5.0.1 on 2024-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_customuser_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qoute',
            field=models.TextField(blank=True, null=True),
        ),
    ]
